/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author gelad
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuMateriais = new javax.swing.JMenu();
        menuCadastroMat = new javax.swing.JMenuItem();
        menuConsultMat = new javax.swing.JMenuItem();
        menuPessoas = new javax.swing.JMenu();
        menuCadPessoas = new javax.swing.JMenuItem();
        menuConsultPessoas = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        menuFazerReserva = new javax.swing.JMenuItem();
        menuConsultReserva = new javax.swing.JMenuItem();
        menuFimReserva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        menuCadastros.setText("Cadastros   |");

        menuMateriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_inventory_maintenance_product_box_boxes_2326 (1).png"))); // NOI18N
        menuMateriais.setText("Materiais");

        menuCadastroMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/businesspackage_additionalpackage_box_add_insert_negoci_2335.png"))); // NOI18N
        menuCadastroMat.setText("Cadastrar");
        menuMateriais.add(menuCadastroMat);

        menuConsultMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_locate_find_6278.png"))); // NOI18N
        menuConsultMat.setText("Consultar");
        menuMateriais.add(menuConsultMat);

        menuCadastros.add(menuMateriais);

        menuPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bootloader_users_person_people_6080.png"))); // NOI18N
        menuPessoas.setText("funcionarios / alunos");

        menuCadPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        menuCadPessoas.setText("Cadastrar");
        menuPessoas.add(menuCadPessoas);

        menuConsultPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_man_usersearch_thesearch_theclient_2356.png"))); // NOI18N
        menuConsultPessoas.setText("Consultar");
        menuPessoas.add(menuConsultPessoas);

        menuCadastros.add(menuPessoas);

        jMenuBar1.add(menuCadastros);

        menuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        menuReservas.setText("reservas   |");

        menuFazerReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3592829-calendar-general-month-month-calendar-office-schedule-wall-calendar_107756.png"))); // NOI18N
        menuFazerReserva.setText("Fazer reserva");
        menuReservas.add(menuFazerReserva);

        menuConsultReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3592851-calendar-general-month-month-calendar-office-schedule-wall-calendar_107740.png"))); // NOI18N
        menuConsultReserva.setText("Consultar reserva");
        menuReservas.add(menuConsultReserva);

        menuFimReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3592863-accounting-calculate-calculation-calculator-general-math-office_107744.png"))); // NOI18N
        menuFimReserva.setText("Finalizar reserva");
        menuReservas.add(menuFimReserva);

        jMenuBar1.add(menuReservas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadPessoas;
    private javax.swing.JMenuItem menuCadastroMat;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuConsultMat;
    private javax.swing.JMenuItem menuConsultPessoas;
    private javax.swing.JMenuItem menuConsultReserva;
    private javax.swing.JMenuItem menuFazerReserva;
    private javax.swing.JMenuItem menuFimReserva;
    private javax.swing.JMenu menuMateriais;
    private javax.swing.JMenu menuPessoas;
    private javax.swing.JMenu menuReservas;
    // End of variables declaration//GEN-END:variables
}
